name: ""
nodePort: 30565
replicas: 0
image: itzg/minecraft-server:latest

server:
  type: VANILLA
  version: "LATEST"
  memory: "4G"
  onlineMode: true
  mods: []

resources:
  requests:
    memory: "4Gi"
    cpu: "1"
  limits:
    memory: "6Gi"
    cpu: "2"

storage: 10Gi

pvc:
  create: true

extraEnv: {}

discordGuildId: ""
