apiVersion: v1
kind: Service
metadata:
  name: vanilla-chill
  namespace: games
spec:
  type: NodePort
  selector:
    app: vanilla-chill
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30565
