name: ""
nodePort: 30566
image: itzg/minecraft-server:java21

server:
  type: FABRIC
  version: "1.21.1"
  memory: "8G"
  onlineMode: true
  mods: []

resources:
  requests:
    memory: "8Gi"
    cpu: "1"
  limits:
    memory: "12Gi"
    cpu: "4"

storage: 40Gi

extraEnv:
  JVM_OPTS: "-XX:+UseZGC -XX:+ZGenerational"
