name: ""
nodePort: 30567
image: itzg/minecraft-server:java21

server:
  type: FORGE
  version: "1.21.1"
  memory: "14G"
  onlineMode: true
  mods: []

resources:
  requests:
    memory: "14Gi"
    cpu: "2"
  limits:
    memory: "20Gi"
    cpu: "4"

storage: 100Gi

extraEnv:
  JVM_OPTS: "-XX:+UseZGC -XX:+ZGenerational"
