name: "vanilla-chill"
nodePort: 30565 

server:
  type: VANILLA
  version: "LATEST"
  memory: "8G"
  onlineMode: true
  mods: []

resources:
  requests:
    memory: "8Gi"
    cpu: "2"
  limits:
    memory: "10Gi"
    cpu: "8"

storage: 20Gi

extraEnv:
  JVM_OPTS: "-XX:+UseZGC -XX:+ZGenerational"