name: vanilla-chill
nodePort: 30565

server:
  type: VANILLA
  version: "LATEST"
  memory: "8G"
  onlineMode: true
  mods: []

resources:
  requests:
    memory: "8Gi"
    cpu: "1"
  limits:
    memory: "10Gi"
    cpu: "4"

storage: 20Gi
replicas: 0

pvc:
  create: false   # PVC vanilla-chill-data already exists from Phase 1
